-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-05-31 16:54:49 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE address (
    id              INTEGER NOT NULL,
    country         VARCHAR2(50 CHAR) NOT NULL,
    city            VARCHAR2(50 CHAR) NOT NULL,
    street          VARCHAR2(50 CHAR),
    building_number INTEGER,
    flat_number     INTEGER,
    postal_code     VARCHAR2(10 CHAR)
);

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( id );

CREATE TABLE event (
    id          INTEGER NOT NULL,
    title       VARCHAR2(50) NOT NULL,
    description CLOB,
    owner_id    INTEGER NOT NULL,
    sport_id    INTEGER NOT NULL,
    address_id  INTEGER NOT NULL,
    latitude    NUMBER,
    longitude   NUMBER
);

ALTER TABLE event ADD CONSTRAINT event_pk PRIMARY KEY ( id );

CREATE TABLE participation (
    id       INTEGER NOT NULL,
    user_id  INTEGER NOT NULL,
    event_id INTEGER NOT NULL
);

ALTER TABLE participation ADD CONSTRAINT participation_pk PRIMARY KEY ( id );

CREATE TABLE sport (
    id   INTEGER NOT NULL,
    name VARCHAR2(20) NOT NULL
);

ALTER TABLE sport ADD CONSTRAINT sport_pk PRIMARY KEY ( id );

CREATE TABLE "User" (
    id            INTEGER NOT NULL,
    username      VARCHAR2(20) NOT NULL,
    email         VARCHAR2(50),
    password_hash VARCHAR2(512) NOT NULL
);

ALTER TABLE "User" ADD CONSTRAINT user_pk PRIMARY KEY ( id );

ALTER TABLE event
    ADD CONSTRAINT event_address_fk FOREIGN KEY ( address_id )
        REFERENCES address ( id );

ALTER TABLE event
    ADD CONSTRAINT event_sport_fk FOREIGN KEY ( sport_id )
        REFERENCES sport ( id );

ALTER TABLE event
    ADD CONSTRAINT event_user_fk FOREIGN KEY ( owner_id )
        REFERENCES "User" ( id );

ALTER TABLE participation
    ADD CONSTRAINT participation_event_fk FOREIGN KEY ( event_id )
        REFERENCES event ( id );

ALTER TABLE participation
    ADD CONSTRAINT participation_user_fk FOREIGN KEY ( user_id )
        REFERENCES "User" ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
